### PR TITLE
COMP adding VTK_OVERRIDE everywhere

### PR DESCRIPTION
**Pull request by hina-shah**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @hina-shah 

Whenever you or @msmolens think it is ready, consider creating a PR against the current Slicer source tree.

It would also be great to submit a PR for OpenIGTLink and commit changes for EMSegment (Max has commit access for this one)

I also wonder if anything need to be changed for SlicerDMRI

**Comment by msmolens** [comment]
There are still some `overrides a member function but is not marked 'override'` warnings in Slicer core that show up in a dashboard build: http://slicer.cdash.org/viewBuildError.php?type=1&buildid=1075183

**Comment by hina-shah** [comment]
Updated the commit. The projects that need updates are: OpenIGTLinkIF, EMSegment, MultiVolumeExplorer and ParameterSerializer.

**Comment by jcfr** [comment]
Thanks Hina.

When you have a chance, could you also share a link to the topic updating this projects:
* OpenIGTLinkIF
* MultiVolumeExplorer
* ParameterSerializer.

And a patch updating  EMSegment

**Comment by msmolens** [comment]
Here is the latest run: http://slicer.cdash.org/viewBuildError.php?type=1&buildid=1075829
There may be a couple missing override warnings still in Slicer core, but I will merge this now and re-run the dashboard build now that I fixed some warnings other projects that pollute the warning results.

**Comment by msmolens** [comment]
Here's the run after merging: http://slicer.cdash.org/viewBuildError.php?type=1&buildid=1075830

**Comment by hina-shah** [comment]
Updated OpenIGTLinkIF, MultiVolumeExplorer, EMSegment and DataStore.

**Pull request merged**
