### PR TITLE
COMP: Fixing python 2.7.13 MSVCCompiler locating of modern compilers

### PR DESCRIPTION
**Pull request by adamrankin**
This enables the compilation of NUMPY with VS2015 (and presumably VS2017)

Increasing NUMPY version to 1.13.1

### CODE REVIEW

**Comment by msmolens** [comment]
Thanks! I see that @jcfr removed the python msvc9compiler patch in https://github.com/Slicer/Slicer/commit/f0cb110f75d65bb1f8fcbd334787133239a5c616, but this adds it back. Are we sure that's necessary?

**Comment by adamrankin** [comment]
After scanning that quickly, I see that that was a patch for msvc9compiler. This is a patch for msvccompiler which fixes the path finding for versions of VS >= VS2012.

@jcfr was in the room working with me, and I confirmed that I was doing something useful. I will let him comment on the previous patch removal.

What I can say is that before this, I was unable to compile NUMPY with VS2015, and now I can, so I think it's useful.

**Comment by msmolens** [comment]
Sounds good to me, thanks!

**Comment by msmolens** [comment]
@adamrankin Could be merged into Slicer master or does it depend on something in this branch?

**Comment by jcfr** [comment]
I told @adamrankin I would take care of integrating into master.

Will review and work on it in few mins

**Comment by msmolens** [comment]
@jcfr Thanks!

**Pull request merged**
